#include <iostream>
#include <sstream>
#include <vector>
#include <string>
#include <memory>
#include <iterator>
#include <unordered_set>
#include <typeinfo>
#include <utility>
#include <algorithm>
#include <numeric>
#include <future>
#include <mutex>
#include <cstdlib>
#include <ctime>

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
